build:
    environment:
        php:
            version: 5.6

    dependencies:
        before:
            -
                command: 'mkdir -p build/logs'

    tests:
        override:
            -
                command: 'vendor/bin/tester tests -p php -c ./tests/php.ini-unix --coverage build/logs/clover.xml --coverage-src src'
                coverage:
                    file: build/logs/clover.xml
                    format: php-clover